version: "3"
services:
  tenant-appointment-booker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: yarn b dev