name: "Get Branch Name for workflow"
description: "Get the branch name for the current workflow"
author: "Vincent METTON"

runs:
  using: "composite"
  steps:
    - name: Extract branch name
      if: github.event_name != 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      id: extract_branch
