name: "Build image and push to registry"

on:
  workflow_run:
    workflows: ["validate"]
    types:
      - completed
    branches:
      - main
      - develop
    paths:
      - packages/tenant-appointment-booker/**

  workflow_dispatch:
    paths:
      - packages/tenant-appointment-booker/**

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    if : ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate tags
        id: generate-tags
        uses: ./.github/actions/generate-tags

      - name: Login to Opera-Groupe's Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.REGISTRY_SERVER }}/tenant-appointment-booker
          tags: ${{ env.TAGS }}
          flavor: latest=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-to: type=registry,ref=${{ secrets.REGISTRY_SERVER }}/tenant-appointment-booker/cache,mode=max
          cache-from: type=registry,ref=${{ secrets.REGISTRY_SERVER }}/tenant-appointment-booker/cache,mode=max
          build-args: |
            NODE_ENV=production
            APP_FOLDER=tenant-appointment-booker
