name: "Build image and push to registry for Contractor Extranet"

on:
  workflow_run:
    workflows: ["Validate Contractor Extranet"]
    types:
      - completed
    branches:
      - main
      - develop
    paths:
      - packages/contractor-extranet/**

  workflow_dispatch:
    paths:
      - packages/contractor-extranet/**

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    if : ${{ github.event.workflow_run.conclusion == 'success' }} || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate tags
        id: generate-tags
        uses: ./.github/actions/generate-tags
        with:
          registry_server: ${{ secrets.REGISTRY_SERVER }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workspace: contractor-extranet

      - name: Login to Opera-Groupe's Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_METADATA_OUTPUT_TAGS }}
          cache-to: type=registry,ref=${{ secrets.REGISTRY_SERVER }}/contractor-extranet/cache,mode=max
          cache-from: type=registry,ref=${{ secrets.REGISTRY_SERVER }}/contractor-extranet/cache,mode=max
          build-args: |
            NODE_ENV=production
            APP_FOLDER=contractor-extranet
