name: CI tenant appointment booker

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: yarn workspace tenant-appointment-booker install
      
    - name: Lint application
      run: yarn workspace tenant-appointment-booker lint

    - name: Build application
      run: yarn workspace tenant-appointment-booker build
